# 1. Vendor
FROM composer:2 AS vendor
WORKDIR /app
COPY src/composer.json src/composer.lock ./
RUN composer install \
    --no-dev \
    --prefer-dist \
    --no-interaction \
    --no-progress \
    --no-scripts \
    --optimize-autoloader

# 2. Frontend
FROM node:20-alpine AS frontend
WORKDIR /app
COPY src/package*.json ./
RUN npm ci
COPY src/ .
RUN npm run build

# =========================
# 3. Runtime (PHP-FPM)
# =========================
FROM php:8.4-fpm as php

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install \
        pdo_mysql \
        mbstring \
        bcmath \
        gd \
        zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www
COPY src/ .
COPY --from=vendor /app/vendor ./vendor

COPY --from=frontend /app/public/build ./public/build

RUN chown -R www-data:www-data /var/www \
 && chmod -R 775 storage bootstrap/cache

CMD ["php-fpm"]

# 4. Nginx
FROM nginx:alpine AS nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=php /var/www/public /var/www/public
